import type { CodegenConfig } from "@graphql-codegen/cli";

function defineConfig(v: CodegenConfig) {
  return v;
}

export default defineConfig({
  overwrite: true,
  schema: ["../graph/schema.graphql", "../graph/mutations/*.graphql"],
  documents: ["src/graphql/**/*.js", "src/graphql/**/*.gql"],
  generates: {
    "src/graphql/generated.ts": {
      plugins: [
        {
          add: {
            content: [
              "// Code generated by `pnpm run generate:graphql` command, DO NOT EDIT",
              "/* eslint-disable */",
            ],
          },
        },
        "typescript",
        "typescript-operations",
        "typed-document-node",
      ],
      config: {
        defaultScalarType: "unknown",
        scalars: {
          Time: "string",
          Upload: "File",
          URI: "string",
        },
        avoidOptionals: {
          field: true,
          object: false,
          inputValue: false,
          defaultValue: false,
        },
        nonOptionalTypename: true,
        onlyOperationTypes: true,
        inputMaybeValue: "T | null | undefined",
        arrayInputCoercion: false,
      },
    },
  },
});
