id = "comfyui-queue"
name = "发送至 ComfyUI"
description = "提取图片内置的工作流，更新随机种子并自动发送至 ComfyUI API 重新入列生成，如果配置了 HOOK_IMAGE_SET_LABEL 环境变量则自动更新图片颜色标签"
command = "uv run runner.py comfyui queue"

[directive]
name = "queue"
usage = """
/queue [-j <N>]
和通过图片触发 `发送至 ComfyUI` 入列效果一致

选项：
-j --jobs <N> 发送工作流次数，默认使用 HOOK_JOBS 环境变量值
"""
on_success_action = "REMOVE" # 成功后移除当前指令避免再次触发

[on.post_commit_session]

[on.post_update_note]
ignore_directive = false # 为 true 时忽略 [directive] 约束（即使定义了指令，笔记中未含该指令也依然触发）

[on.image_dispatch]

[env]
# COMFYUI_OUTPUT_DIR = ""  # ComfyUI 的输出根目录。若未提供，自动为图片绝对路径中最后一个名为 output 的目录。显式提供时会校验图片及目标目录是否在其中。
# HOOK_OUTPUT_DIR = ""     # 覆盖目标输出目录。默认不指定时，输出到图片当前所在目录；指定相对路径时，该路径相对于 ComfyUI 的输出根目录；若设为绝对路径，则必须在输出根目录内部，否则报错；若设为 :inherit:，则完全关闭目录自动调整功能。
HOOK_IMAGE_RATING = "4"   # 会话提交后拉取该评分的图片，且仅入列未打标的图片（已打标的视为已入列过）
HOOK_JOBS = "2"
HOOK_IMAGE_SET_LABEL = "Red"
HOOK_MAX_MATCH = "4"
