id = "comfyui-add"
name = "添加 ComfyUI 提示词"
description = "在会话提交时运行 /add 指令，"
command = "uv run comfyui.py add"

[directive]
name = "add"
usage = """
/add [--neg] [--region <region>]... [-j <N>] [--node <node-id>]... [-S] [--raw] <prompt>...
给当前目录所有 4 星图片的 ComfyUI 工作流添加提示词后再将其入列生成。
在会话提交后触发，也可以手动通过笔记触发。
可传入多个提示词，多个提示词会以空格拼接为一个整体后再添加
提示词单独一行

选项：
--neg marker 和 node 都不匹配时，用关键词匹配负面提示词而不是正面
--region <region> 指定插入区域，可多次指定；优先匹配 node，若指定了 region 则插入到对应区域
-j --jobs <N> 发送工作流次数，默认使用 HOOK_JOBS 环境变量值
--node <node-id> 指定插入节点，可多次指定；优先匹配 node
-S --no-skip 即使提示词已存在也要执行，不指定时会跳过已存在对应提示词的图片
--raw 不给提示词附加尾随逗号
未指定 --region 和 --node 时，默认使用 positive 区域（指定 --neg 时使用 negative 区域）
"""
on_success_action = "COMMENT_OUT" # 成功后把当前指令用 %% /add ... %% 注释掉避免再次触发

[directive.autocomplete]
command = "uv run comfyui.py autocomplete"

[on.post_commit_session.note_scan]  # 会话提交后，扫描目录内笔记，对每一个笔记触发钩子逻辑
ignore_directive = false # 为 true 时忽略 [directive] 约束（即使定义了指令，笔记中未含该指令也依然触发）

[on.note_dispatch]

[env]
# COMFYUI_OUTPUT_DIR = ""  # ComfyUI 的输出根目录。若未提供，自动为图片绝对路径中最后一个名为 output 的目录。显式提供时会校验图片及目标目录是否在其中。
# HOOK_OUTPUT_DIR = ""     # 覆盖目标输出目录。默认不指定时，输出到图片当前所在目录；指定相对路径时，该路径相对于 ComfyUI 的输出根目录；若设为绝对路径，则必须在输出根目录内部，否则报错；若设为 :inherit:，则完全关闭目录自动调整功能。
HOOK_START_REGION_PREFIX = "//#region "
HOOK_END_REGION_PREFIX = "//#endregion "
HOOK_IMAGE_RATING = "4"
HOOK_JOBS = "4"
HOOK_MAX_MATCH = "4"
HOOK_POSITIVE_KEYWORDS = "masterpiece, best quality, score_7"
HOOK_NEGATIVE_KEYWORDS = "worst quality, low quality, score_1, score_2, score_3"
