id = "comfyui-add"
name = "添加 ComfyUI 提示词"
description = "在会话提交时运行 /add 指令，"
command = "python comfyui.py add"

[directive]
name = "add"
usage = """
/add [--no-skip] [--neg] [--raw] <prompt>...
给当前目录所有 4 星图片的 ComfyUI 工作流添加提示词后再将其入列生成。
在会话提交后触发，也可以手动通过笔记触发。
插入位置默认为　Marker 标记的区域位置，如果没找到则尝试自动找到正向提示词位置的输入位置并添加标记，找不到则报错
可传入多个提示词，多个提示词会以空格拼接为一个整体后再添加
提示词单独一行

选项：
--neg 添加到负面提示词而不是正面
-S --no-skip 即使提示词已存在也要执行，不指定时会跳过已存在对应提示词的图片
--raw 不给提示词附加尾随逗号
"""
on_success_action = "COMMENT_OUT" # 成功后把当前指令用 %% /add ... %% 注释掉避免再次触发

[on.post_commit_session.memo_scan]  # 会话提交后，扫描目录内笔记，对每一个笔记触发钩子逻辑
ignore_directive = false # 为 true 时忽略 [directive] 约束（即使定义了指令，备忘录中未含该指令也依然触发）

[on.memo_dispatch]

[env]
HOOK_POSITIVE_START_MARKER = "//#region hook-positive"
HOOK_POSITIVE_END_MARKER = "//#endregion hook-positive"
HOOK_NEGATIVE_START_MARKER = "//#region hook-negative"
HOOK_NEGATIVE_END_MARKER = "//#endregion hook-negative"
HOOK_IMAGE_RATING = "4"
HOOK_QUEUE_COUNT = "4"
HOOK_POSITIVE_KEYWORDS = "masterpiece, best quality, score_7"
HOOK_NEGATIVE_KEYWORDS = "worst quality, low quality, score_1, score_2, score_3"
