fragment DirectoryState on DirectoryState {
  browse {
    filterBy {
      id
      rating
      label
      query
    }
    filterNoteBy {
      id
      hidden
    }
  }
  lastSession {
    id
    filter {
      id
      rating
      label
      query
    }
    targetKeep
  }
  default {
    writeActions {
      keepRating
      shelveRating
      rejectRating
    }
  }
  updatedAt
}
