fragment Directory on Directory {
  id
  parentId
  relPath
  root
  lastSession {
    id
    filter {
      id
      rating
      label
      query
    }
    targetKeep
  }
  state {
    lastSession {
      id
      filter {
        id
        rating
        label
        query
      }
      targetKeep
    }
  }
}
