fragment Image on Image {
  id
  filename
  url
  rawURL
  url256: url(width: 256)
  url512: url(width: 512)
  url1024: url(width: 1024)
  url2048: url(width: 2048)
  url4096: url(width: 4096)
  modTime
  width
  height
  size
  currentRating
  label
  relPath
  note {
    ...Note
  }
}