fragment ImageFragment on Image {
  id
  filename
  url
  url256: url(width: 256, quality: 50)
  url512: url(width: 512, quality: 60)
  url1024: url(width: 1024, quality: 70)
  url2048: url(width: 2048, quality: 80)
  url4096: url(width: 4096, quality: 90)
  modTime
  width
  height
}
