#import './StatsFragment.gql'
#import './ImageFragment.gql'

fragment SessionFragment on Session {
  id
  directory
  filter {
    rating
  }
  targetKeep
  stats {
    ...StatsFragment
  }
  createdAt
  updatedAt
  canCommit
  canUndo
  currentIndex
  currentSize
  currentImage {
    ...ImageFragment
  }
}
