#import './StatsFragment.gql'
#import './ImageFragment.gql'

fragment SessionFragment on Session {
  id
  directory
  filter {
    rating
  }
  targetKeep
  status
  stats {
    ...StatsFragment
  }
  createdAt
  updatedAt
  canCommit
  canUndo
  currentImage {
    ...ImageFragment
  }
  queueStatus {
    currentIndex
    totalImages
    progress
  }
}
