fragment Session on Session {
  id
  directory {
    ...Directory
  }
  filter {
    id
    directoryId
    rating
    label
    query
  }
  targetKeep
  stats {
    ...SessionStats
  }
  createdAt
  updatedAt
  canCommit
  canUndo
  currentIndex
  currentSize
  currentRound
  currentImage {
    ...Image
  }
  nextImages(count: 10) {
    ...Image
  }
  currentRoundActions
}
