fragment Session on Session {
  id
  directory
  filter {
    rating
  }
  targetKeep
  stats {
    ...SessionStats
  }
  createdAt
  updatedAt
  canCommit
  canUndo
  currentIndex
  currentSize
  currentImage {
    ...Image
  }
  nextImage {
    ...Image
  }
}
