package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// CommitChanges is the resolver for the commitChanges field.
func (r *mutationResolver) CommitChanges(ctx context.Context, input CommitChangesInput) (*CommitChangesPayload, error) {
	success, errors := r.App.Commit(
		ctx,
		input.SessionID,
		input.WriteActions.KeepRating,
		input.WriteActions.PendingRating,
		input.WriteActions.RejectRating,
	)

	sess, err := r.App.GetSession(ctx, input.SessionID)
	if err != nil {
		return nil, err
	}

	var errorStrings []string
	for _, err := range errors {
		errorStrings = append(errorStrings, err.Error())
	}

	return &CommitChangesPayload{
		Success:          len(errors) == 0,
		Written:          success,
		Failed:           len(errors),
		Errors:           errorStrings,
		Session:          sess,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
