package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// CommitChanges is the resolver for the commitChanges field.
func (r *mutationResolver) CommitChanges(ctx context.Context, input CommitChangesInput) (*CommitChangesPayload, error) {
	success, errors := r.Resolver.SessionManager.Commit(input.SessionID, input.WriteActions)

	var errorStrings []string
	for _, err := range errors {
		errorStrings = append(errorStrings, err.Error())
	}

	sess, exists := r.Resolver.SessionManager.Get(input.SessionID)
	var session *Session
	if exists {
		session = r.Resolver.convertToGQLSession(sess)
		r.Resolver.SessionTopic.Publish(ctx, session)
	}

	return &CommitChangesPayload{
		Success:          len(errors) == 0,
		Written:          success,
		Failed:           len(errors),
		Errors:           errorStrings,
		Session:          session,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
