package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"main/internal/scanner"
	"path/filepath"
)

// CreateSession is the resolver for the createSession field.
func (r *mutationResolver) CreateSession(ctx context.Context, input CreateSessionInput) (*CreateSessionPayload, error) {
	p, exists := r.Resolver.PresetManager.GetByID(input.PresetID)
	if !exists {
		return nil, fmt.Errorf("preset not found")
	}

	s := scanner.NewScanner(r.RootDir)
	if err := s.ValidateDirectoryPath(input.Directory); err != nil {
		return nil, fmt.Errorf("invalid directory: %w", err)
	}

	dirPath := filepath.Join(r.RootDir, input.Directory)

	sess, err := r.Resolver.SessionManager.Create(dirPath, p, input.TargetKeep)
	if err != nil {
		return nil, err
	}

	return &CreateSessionPayload{
		Session:          r.Resolver.convertToGQLSession(sess),
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
