package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"main/internal/session"
)

// MarkImage is the resolver for the markImage field.
func (r *mutationResolver) MarkImage(ctx context.Context, input MarkImageInput) (*MarkImagePayload, error) {
	var sessAction session.Action
	switch input.Action {
	case ImageActionKeep:
		sessAction = session.ActionKeep
	case ImageActionPending:
		sessAction = session.ActionPending
	case ImageActionReject:
		sessAction = session.ActionReject
	default:
		return nil, fmt.Errorf("invalid action")
	}

	_, _, err := r.Resolver.SessionManager.MarkImage(input.SessionID, input.ImageID, sessAction)
	if err != nil {
		return nil, err
	}

	sess, _ := r.Resolver.SessionManager.Get(input.SessionID)
	gqlSession := r.Resolver.convertToGQLSession(sess)
	r.Resolver.SessionTopic.Publish(ctx, gqlSession)

	return &MarkImagePayload{
		Session:          gqlSession,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
