// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"main/internal/session"
	"strconv"
	"time"
)

type CommitChangesInput struct {
	SessionID        string                `json:"sessionId"`
	WriteActions     *session.WriteActions `json:"writeActions"`
	ClientMutationID *string               `json:"clientMutationId,omitempty"`
}

type CommitChangesPayload struct {
	Success          bool     `json:"success"`
	Written          int      `json:"written"`
	Failed           int      `json:"failed"`
	Errors           []string `json:"errors"`
	Session          *Session `json:"session,omitempty"`
	ClientMutationID *string  `json:"clientMutationId,omitempty"`
}

type CreateSessionInput struct {
	Filter           *session.ImageFilters `json:"filter"`
	TargetKeep       int                   `json:"targetKeep"`
	Directory        string                `json:"directory"`
	ClientMutationID *string               `json:"clientMutationId,omitempty"`
}

type CreateSessionPayload struct {
	Session          *Session `json:"session"`
	ClientMutationID *string  `json:"clientMutationId,omitempty"`
}

type Directory struct {
	ID                 string    `json:"id"`
	Path               string    `json:"path"`
	ImageCount         int       `json:"imageCount"`
	SubdirectoryCount  int       `json:"subdirectoryCount"`
	LatestImageModTime time.Time `json:"latestImageModTime"`
	LatestImagePath    *string   `json:"latestImagePath,omitempty"`
	LatestImageURL     *string   `json:"latestImageUrl,omitempty"`
}

type Image struct {
	ID            string `json:"id"`
	Filename      string `json:"filename"`
	Size          int    `json:"size"`
	URL           string `json:"url"`
	CurrentRating *int   `json:"currentRating,omitempty"`
	XmpExists     bool   `json:"xmpExists"`
}

type MarkImageInput struct {
	SessionID        string      `json:"sessionId"`
	ImageID          string      `json:"imageId"`
	Action           ImageAction `json:"action"`
	ClientMutationID *string     `json:"clientMutationId,omitempty"`
}

type MarkImagePayload struct {
	Session          *Session `json:"session"`
	ClientMutationID *string  `json:"clientMutationId,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type QueueStatus struct {
	CurrentIndex int     `json:"currentIndex"`
	TotalImages  int     `json:"totalImages"`
	CurrentImage *Image  `json:"currentImage,omitempty"`
	Progress     float64 `json:"progress"`
}

type Session struct {
	ID           string                `json:"id"`
	Directory    string                `json:"directory"`
	Filter       *session.ImageFilters `json:"filter"`
	TargetKeep   int                   `json:"targetKeep"`
	Status       SessionStatus         `json:"status"`
	Stats        *SessionStats         `json:"stats"`
	CreatedAt    string                `json:"createdAt"`
	UpdatedAt    string                `json:"updatedAt"`
	CanCommit    bool                  `json:"canCommit"`
	CanUndo      bool                  `json:"canUndo"`
	CurrentImage *Image                `json:"currentImage,omitempty"`
	QueueStatus  *QueueStatus          `json:"queueStatus"`
}

type SessionStats struct {
	Total     int `json:"total"`
	Processed int `json:"processed"`
	Kept      int `json:"kept"`
	Reviewed  int `json:"reviewed"`
	Rejected  int `json:"rejected"`
	Remaining int `json:"remaining"`
}

type Subscription struct {
}

type UndoInput struct {
	SessionID        string  `json:"sessionId"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type UndoPayload struct {
	Session          *Session `json:"session,omitempty"`
	ClientMutationID *string  `json:"clientMutationId,omitempty"`
}

type ImageAction string

const (
	ImageActionKeep    ImageAction = "KEEP"
	ImageActionPending ImageAction = "PENDING"
	ImageActionReject  ImageAction = "REJECT"
)

var AllImageAction = []ImageAction{
	ImageActionKeep,
	ImageActionPending,
	ImageActionReject,
}

func (e ImageAction) IsValid() bool {
	switch e {
	case ImageActionKeep, ImageActionPending, ImageActionReject:
		return true
	}
	return false
}

func (e ImageAction) String() string {
	return string(e)
}

func (e *ImageAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ImageAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ImageAction", str)
	}
	return nil
}

func (e ImageAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ImageAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ImageAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionStatus string

const (
	SessionStatusInitializing SessionStatus = "INITIALIZING"
	SessionStatusActive       SessionStatus = "ACTIVE"
	SessionStatusPaused       SessionStatus = "PAUSED"
	SessionStatusCompleted    SessionStatus = "COMPLETED"
	SessionStatusCommitting   SessionStatus = "COMMITTING"
	SessionStatusError        SessionStatus = "ERROR"
)

var AllSessionStatus = []SessionStatus{
	SessionStatusInitializing,
	SessionStatusActive,
	SessionStatusPaused,
	SessionStatusCompleted,
	SessionStatusCommitting,
	SessionStatusError,
}

func (e SessionStatus) IsValid() bool {
	switch e {
	case SessionStatusInitializing, SessionStatusActive, SessionStatusPaused, SessionStatusCompleted, SessionStatusCommitting, SessionStatusError:
		return true
	}
	return false
}

func (e SessionStatus) String() string {
	return string(e)
}

func (e *SessionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionStatus", str)
	}
	return nil
}

func (e SessionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
