package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, id string) (*Session, error) {
	return r.Resolver.Session(ctx, id)
}

// Directories is the resolver for the directories field.
func (r *queryResolver) Directories(ctx context.Context, path string) ([]*Directory, error) {
	return r.Resolver.Directories(ctx, path)
}

// SessionUpdated is the resolver for the sessionUpdated field.
func (r *subscriptionResolver) SessionUpdated(ctx context.Context, sessionID string) (<-chan *Session, error) {
	return r.Resolver.SessionUpdated(ctx, sessionID)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
