package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"
)

// UpdatePreset is the resolver for the updatePreset field.
func (r *mutationResolver) UpdatePreset(ctx context.Context, input UpdatePresetInput) (*UpdatePresetPayload, error) {
	p, exists := r.Resolver.PresetManager.GetByID(input.PresetID)
	if !exists {
		return nil, fmt.Errorf("preset not found")
	}

	sess, exists := r.Resolver.SessionManager.Get(input.SessionID)
	if !exists {
		return nil, fmt.Errorf("session not found")
	}

	sess.Preset = p
	sess.UpdatedAt = time.Now()

	return &UpdatePresetPayload{
		Session:          r.Resolver.convertToGQLSession(sess),
		ClientMutationID: input.ClientMutationID,
	}, nil
}
