package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// ApprovePairingRequest is the resolver for the approvePairingRequest field.
func (r *mutationResolver) ApprovePairingRequest(ctx context.Context, input ApprovePairingRequestInput) (*ApprovePairingRequestPayload, error) {
	err := r.app.ApprovePairingRequest(ctx, input.Code)
	if err != nil {
		return nil, err
	}
	return &ApprovePairingRequestPayload{
		ClientMutationID: input.ClientMutationID,
	}, nil
}
