package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// AttachFileToClipboard is the resolver for the attachFileToClipboard field.
func (r *mutationResolver) AttachFileToClipboard(ctx context.Context, input AttachFileToClipboardInput) (*AttachFileToClipboardPayload, error) {
	result, err := r.app.AttachFileToClipboard(ctx, input.Paths, input.Nonce)
	if err != nil {
		return nil, err
	}

	return &AttachFileToClipboardPayload{
		Supported:        result.Supported,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
