package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// AuthStatus is the resolver for the authStatus field.
func (r *queryResolver) AuthStatus(ctx context.Context) (*AuthStatus, error) {
	status, err := r.app.AuthStatus(ctx)
	if err != nil {
		return nil, err
	}
	return &AuthStatus{
		IsTrustedDevice: status.IsTrustedDevice,
		IsTrustedIP:     status.IsTrustedIP,
		CanAccess:       status.CanAccess,
		ClientIP:        status.ClientIP,
	}, nil
}
