package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// BeginWebAuthnLogin is the resolver for the beginWebAuthnLogin field.
func (r *mutationResolver) BeginWebAuthnLogin(ctx context.Context, input BeginWebAuthnLoginInput) (*BeginWebAuthnLoginPayload, error) {
	options, sessionKey, err := r.app.BeginWebAuthnLogin(ctx)
	if err != nil {
		return nil, err
	}
	return &BeginWebAuthnLoginPayload{
		// 只返回 PublicKeyCredentialRequestOptions，不含外层的 publicKey 包装
		Options:    options.Response,
		SessionKey: sessionKey,
	}, nil
}
