package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// BeginWebAuthnRegistration is the resolver for the beginWebAuthnRegistration field.
func (r *mutationResolver) BeginWebAuthnRegistration(ctx context.Context, input BeginWebAuthnRegistrationInput) (*BeginWebAuthnRegistrationPayload, error) {
	options, sessionKey, err := r.app.BeginWebAuthnRegistration(ctx)
	if err != nil {
		return nil, err
	}
	return &BeginWebAuthnRegistrationPayload{
		// 只返回 PublicKeyCredentialCreationOptions，不含外层的 publicKey 包装
		Options:    options.Response,
		SessionKey: sessionKey,
	}, nil
}
