package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
)

// ComfyUIWorkflow is the resolver for the comfyUIWorkflow field.
func (r *queryResolver) ComfyUIWorkflow(ctx context.Context, id scalar.ID) (*string, error) {
	return r.app.ComfyUIWorkflow(ctx, id)
}
