package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

// CommitChanges is the resolver for the commitChanges field.
func (r *mutationResolver) CommitChanges(ctx context.Context, input CommitChangesInput) (*CommitChangesPayload, error) {
	written, err := r.app.Commit(
		ctx,
		input.SessionID,
		input.WriteActions.KeepRating,
		input.WriteActions.ShelveRating,
		input.WriteActions.RejectRating,
	)
	if err != nil {
		graphql.AddError(ctx, err)
	}

	sess, sessErr := r.app.Session(ctx, input.SessionID)
	if sessErr != nil {
		return nil, sessErr
	}

	return &CommitChangesPayload{
		Written:          written,
		Session:          sess,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
