package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// CreateNote is the resolver for the createNote field.
func (r *mutationResolver) CreateNote(ctx context.Context, input CreateNoteInput) (*CreateNotePayload, error) {
	note, err := r.app.CreateNote(ctx, input.DirectoryID, input.Name, input.Content)
	if err != nil {
		return nil, err
	}
	return &CreateNotePayload{
		Note:             note,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
