package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// CreateSession is resolver for the createSession field.
func (r *mutationResolver) CreateSession(ctx context.Context, input CreateSessionInput) (*CreateSessionPayload, error) {
	sessionID, err := r.app.CreateSession(
		ctx,
		input.DirectoryID,
		input.Filter,
		input.TargetKeep,
	)
	if err != nil {
		return nil, err
	}

	sess, err := r.app.GetSession(ctx, sessionID)
	if err != nil {
		return nil, err
	}

	return &CreateSessionPayload{
		Session:          sess,
		ClientMutationID: input.ClientMutationID,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
