package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// DeleteDevice is the resolver for the deleteDevice field.
func (r *mutationResolver) DeleteDevice(ctx context.Context, input DeleteDeviceInput) (bool, error) {
	err := r.app.Delete(ctx, input.ID)
	return err == nil, err
}
