package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// Devices is the resolver for the devices field.
func (r *queryResolver) Devices(ctx context.Context) ([]*shared.DeviceDTO, error) {
	return r.app.List(ctx)
}
