package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// DeviceSaved is the resolver for the deviceSaved field.
func (r *subscriptionResolver) DeviceSaved(ctx context.Context) (<-chan *shared.DeviceDTO, error) {
	return SubscriptionFromSeq(ctx, func(yield func(*shared.DeviceDTO, error) bool) {
		for dto, err := range r.app.SubscribeSaved(ctx) {
			if err != nil {
				if !yield(nil, err) {
					return
				}
				continue
			}
			if !yield(dto, nil) {
				return
			}
		}
	})
}
