package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	appdevice "main/internal/application/device"
	"main/internal/shared"
)

// IsCurrent is the resolver for the isCurrent field.
func (r *deviceResolver) IsCurrent(ctx context.Context, obj *shared.DeviceDTO) (bool, error) {
	currentID, hasCurrent := appdevice.TrustedDeviceID(ctx)
	return hasCurrent && obj.ID == currentID, nil
}

// Device returns DeviceResolver implementation.
func (r *Resolver) Device() DeviceResolver { return &deviceResolver{r} }

type deviceResolver struct{ *Resolver }
