package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
)

// DeviceDeleted is the resolver for the deviceDeleted field.
func (r *subscriptionResolver) DeviceDeleted(ctx context.Context) (<-chan *scalar.ID, error) {
	return SubscriptionFromSeq(ctx, func(yield func(*scalar.ID, error) bool) {
		for id, err := range r.app.SubscribeDeleted(ctx) {
			if err != nil {
				if !yield(nil, err) {
					return
				}
				continue
			}
			val := id
			if !yield(&val, nil) {
				return
			}
		}
	})
}
