package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
	"main/internal/shared"
)

// DirEntryDeleted is the resolver for the dirEntryDeleted field.
func (r *subscriptionResolver) DirEntryDeleted(ctx context.Context, directoryID *scalar.ID) (<-chan *shared.DirEntryDeletedDTO, error) {
	return SubscriptionFromSeq(ctx, r.app.DirEntryDeleted(ctx, directoryID))
}
