package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
	"main/internal/util"
)

// DirectoryChanged is the resolver for the directoryChanged field.
func (r *subscriptionResolver) DirectoryChanged(ctx context.Context, filterBy *shared.DirectoryFilters) (<-chan *shared.DirectoryDTO, error) {
	return SubscriptionFromSeq(ctx, r.app.DirectoryChanged(ctx, util.UnwrapPointer(filterBy)))
}
