package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
	"main/internal/shared"
)

// Stats is the resolver for the stats field.
func (r *directoryResolver) Stats(ctx context.Context, obj *shared.DirectoryDTO) (*shared.DirectoryStatsDTO, error) {
	return r.app.GetDirectoryStats(ctx, obj.ID)
}

// Directories is the resolver for the directories field.
func (r *directoryResolver) Directories(ctx context.Context, obj *shared.DirectoryDTO) ([]*shared.DirectoryDTO, error) {
	return r.app.GetDirectories(ctx, obj.ID)
}

// Directory is the resolver for the directory field.
func (r *queryResolver) Directory(ctx context.Context, id *scalar.ID) (*shared.DirectoryDTO, error) {
	if id == nil {
		return r.app.GetDirectory(ctx, scalar.ID{})
	}
	return r.app.GetDirectory(ctx, *id)
}

// Directory returns DirectoryResolver implementation.
func (r *Resolver) Directory() DirectoryResolver { return &directoryResolver{r} }

type directoryResolver struct{ *Resolver }
