package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// Stats is the resolver for the stats field.
func (r *directoryResolver) Stats(ctx context.Context, obj *shared.DirectoryDTO) (*shared.DirectoryStatsDTO, error) {
	return r.app.DirectoryStats(ctx, obj.ID)
}

// Directories is the resolver for the directories field.
func (r *directoryResolver) Directories(ctx context.Context, obj *shared.DirectoryDTO) ([]*shared.DirectoryDTO, error) {
	return r.app.Directories(ctx, obj.ID)
}

// Directory returns DirectoryResolver implementation.
func (r *Resolver) Directory() DirectoryResolver { return &directoryResolver{r} }

type directoryResolver struct{ *Resolver }
