package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// CommitActions is the resolver for the commitActions field.
func (r *directoryStateLastSessionResolver) CommitActions(ctx context.Context, obj *shared.DirectoryStateLastSessionDTO) (*shared.WriteActions, error) {
	return nil, nil
}

// CreateActions is the resolver for the createActions field.
func (r *directoryStateLastSessionResolver) CreateActions(ctx context.Context, obj *shared.DirectoryStateLastSessionDTO) (*shared.WriteActions, error) {
	return nil, nil
}

// CreateActions is the resolver for the createActions field.
func (r *directoryStateLastSessionInputResolver) CreateActions(ctx context.Context, obj *shared.DirectoryStateLastSessionDTO, data *shared.WriteActions) error {
	return nil
}

// DirectoryStateLastSession returns DirectoryStateLastSessionResolver implementation.
func (r *Resolver) DirectoryStateLastSession() DirectoryStateLastSessionResolver {
	return &directoryStateLastSessionResolver{r}
}

// DirectoryStateLastSessionInput returns DirectoryStateLastSessionInputResolver implementation.
func (r *Resolver) DirectoryStateLastSessionInput() DirectoryStateLastSessionInputResolver {
	return &directoryStateLastSessionInputResolver{r}
}

type directoryStateLastSessionResolver struct{ *Resolver }
type directoryStateLastSessionInputResolver struct{ *Resolver }
