package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/pagination"
	"main/internal/shared"
	"main/internal/util"
)

// Stats is the resolver for the stats field.
func (r *directoryResolver) Stats(ctx context.Context, obj *shared.DirectoryDTO) (*shared.DirectoryStatsDTO, error) {
	return r.app.DirectoryStats(ctx, obj.ID)
}

// Directories is the resolver for the directories field.
func (r *directoryResolver) Directories(ctx context.Context, obj *shared.DirectoryDTO) ([]*shared.DirectoryDTO, error) {
	conn, err := r.app.Directories(ctx, obj.ID, shared.DirectoryFilters{}, &pagination.MaxPageSize, nil)
	if err != nil {
		return nil, err
	}
	return conn.Nodes, nil
}

// DirectoriesV2 is the resolver for the directoriesV2 field.
func (r *directoryResolver) DirectoriesV2(ctx context.Context, obj *shared.DirectoryDTO, filterBy *shared.DirectoryFilters, first *int, after *string) (*shared.DirectoryConnectionDTO, error) {
	return r.app.Directories(ctx, obj.ID, util.UnwrapPointer(filterBy), first, after)
}

// Images is the resolver for the images field.
func (r *directoryResolver) Images(ctx context.Context, obj *shared.DirectoryDTO, filterBy *shared.ImageFilters, first *int, after *string) (*shared.ImageConnectionDTO, error) {
	var filters shared.ImageFilters
	if filterBy != nil {
		filters = *filterBy
	}
	return r.app.Images(ctx, obj.ID, filters, first, after)
}

// Memos is the resolver for the memos field.
func (r *directoryResolver) Memos(ctx context.Context, obj *shared.DirectoryDTO, filterBy *shared.MemoFilters, first *int, after *string) (*shared.MemoConnectionDTO, error) {
	var filters shared.MemoFilters
	if filterBy != nil {
		filters = *filterBy
	}
	return r.app.Memos(ctx, obj.ID, filters, first, after)
}

// LastSession is the resolver for the lastSession field.
func (r *directoryResolver) LastSession(ctx context.Context, obj *shared.DirectoryDTO) (*shared.SessionDTO, error) {
	return r.app.LastSession(ctx, obj.ID)
}

// Directory returns DirectoryResolver implementation.
func (r *Resolver) Directory() DirectoryResolver { return &directoryResolver{r} }

type directoryResolver struct{ *Resolver }
