package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// RatingCounts is the resolver for the ratingCounts field.
func (r *directoryStatsResolver) RatingCounts(ctx context.Context, obj *shared.DirectoryStatsDTO) ([]*RatingCount, error) {
	var result []*RatingCount
	for rating, count := range obj.RatingCounts {
		result = append(result, &RatingCount{
			Rating: rating,
			Count:  count,
		})
	}
	return result, nil
}

// DirectoryStats returns DirectoryStatsResolver implementation.
func (r *Resolver) DirectoryStats() DirectoryStatsResolver { return &directoryStatsResolver{r} }

type directoryStatsResolver struct{ *Resolver }
