package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// DispatchMemoHook is the resolver for the dispatchMemoHook field.
func (r *mutationResolver) DispatchMemoHook(ctx context.Context, input DispatchMemoHookInput) (*DispatchMemoHookPayload, error) {
	memo, err := r.app.Memo(ctx, input.MemoID)
	if err != nil {
		return nil, err
	}

	err = r.app.DispatchMemo(ctx, memo.RelPath, input.HookID)
	if err != nil {
		return nil, err
	}

	return &DispatchMemoHookPayload{
		ClientMutationID: input.ClientMutationID,
	}, nil
}
