package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// DispatchNoteHook is the resolver for the dispatchNoteHook field.
func (r *mutationResolver) DispatchNoteHook(ctx context.Context, input DispatchNoteHookInput) (*DispatchNoteHookPayload, error) {
	note, err := r.app.Note(ctx, input.NoteID)
	if err != nil {
		return nil, err
	}

	err = r.app.DispatchNote(ctx, note.RelPath, input.HookID)
	if err != nil {
		return nil, err
	}

	return &DispatchNoteHookPayload{
		ClientMutationID: input.ClientMutationID,
	}, nil
}
