package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// DispatchImageHook is the resolver for the dispatchImageHook field.
func (r *mutationResolver) DispatchImageHook(ctx context.Context, input DispatchImageHookInput) (*DispatchImageHookPayload, error) {
	var ids []string
	for _, id := range input.Ids {
		if id != nil {
			ids = append(ids, id.String())
		}
	}

	err := r.app.Dispatch(ctx, ids, input.HookID, "image_dispatch")
	if err != nil {
		return nil, err
	}
	return &DispatchImageHookPayload{
		ClientMutationID: input.ClientMutationID,
	}, nil
}
