package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// EmptyTrash is the resolver for the emptyTrash field.
func (r *mutationResolver) EmptyTrash(ctx context.Context, input EmptyTrashInput) (*shared.EmptyTrashResultDTO, error) {
	result, err := r.app.EmptyTrash(ctx, input.MinAge)
	if err != nil {
		return nil, err
	}

	result.ClientMutationID = input.ClientMutationID
	return result, nil
}
