package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"time"
)

// FinishWebAuthnRegistration is the resolver for the finishWebAuthnRegistration field.
func (r *mutationResolver) FinishWebAuthnRegistration(ctx context.Context, input FinishWebAuthnRegistrationInput) (*FinishWebAuthnRegistrationPayload, error) {
	setupToken := ""
	if input.SetupToken != nil {
		setupToken = *input.SetupToken
	}
	device, pr, accessTokenRef, refreshTokenRef, accessExpiresAt, refreshExpiresAt, err := r.app.FinishWebAuthnRegistration(ctx, input.SessionKey, input.Response, setupToken)
	if err != nil {
		return nil, err
	}

	payload := &FinishWebAuthnRegistrationPayload{
		ClientMutationID: input.ClientMutationID,
	}
	if accessTokenRef != "" {
		payload.AccessToken = &accessTokenRef
		accessExpIn := int(time.Until(accessExpiresAt).Seconds())
		payload.AccessTokenExpiresIn = &accessExpIn
		payload.RefreshToken = &refreshTokenRef
		refreshExpIn := int(time.Until(refreshExpiresAt).Seconds())
		payload.RefreshTokenExpiresIn = &refreshExpIn
	}
	if device != nil {
		payload.Device = device
	}
	if pr != nil {
		payload.PairingRequest = pr
	}
	return payload, nil
}
