package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	appdevice "main/internal/application/device"
	"time"
)

// FinishWebAuthnLogin is the resolver for the finishWebAuthnLogin field.
func (r *mutationResolver) FinishWebAuthnLogin(ctx context.Context, input FinishWebAuthnLoginInput) (*FinishWebAuthnLoginPayload, error) {
	ip := appdevice.RemoteIP(ctx)
	accessTokenRef, refreshTokenRef, accessExpiresAt, refreshExpiresAt, device, err := r.app.FinishWebAuthnLogin(ctx, input.SessionKey, input.Response, ip)
	if err != nil {
		return nil, err
	}
	return &FinishWebAuthnLoginPayload{
		AccessToken:           accessTokenRef,
		AccessTokenExpiresIn:  int(time.Until(accessExpiresAt).Seconds()),
		RefreshToken:          refreshTokenRef,
		RefreshTokenExpiresIn: int(time.Until(refreshExpiresAt).Seconds()),
		Device:                device,
	}, nil
}
