package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// HookAutocomplete is the resolver for the hookAutocomplete field.
func (r *queryResolver) HookAutocomplete(ctx context.Context, input HookAutocompleteInput) ([]*shared.AutocompleteSuggestionDTO, error) {
	note, err := r.app.Note(ctx, input.NoteID)
	if err != nil {
		return nil, err
	}

	return r.app.Autocomplete(ctx, input.HookID, note.RelPath, input.LinePrefix, input.Query)
}
