package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// Hooks is the resolver for the hooks field.
func (r *queryResolver) Hooks(ctx context.Context) ([]*shared.HookDTO, error) {
	return r.app.Hooks(ctx)
}
