package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
	"main/internal/util"
)

// HookAutocomplete is the resolver for the hookAutocomplete field.
func (r *queryResolver) HookAutocomplete(ctx context.Context, input HookAutocompleteInput) ([]*shared.AutocompleteSuggestionDTO, error) {
	noteID := util.UnwrapPointer(input.NoteID)
	var noteRelPath string
	if !noteID.IsZero() {
		note, err := r.app.Note(ctx, noteID)
		if err != nil {
			return nil, err
		}
		noteRelPath = note.RelPath
	}

	return r.app.Autocomplete(ctx, input.HookID, noteRelPath, input.LinePrefix, input.Query)
}
