package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// ImageSaved is the resolver for the imageSaved field.
func (r *subscriptionResolver) ImageSaved(ctx context.Context, filterBy *shared.ImageFilters) (<-chan *shared.ImageDTO, error) {
	return SubscriptionFromSeq(ctx, r.app.ImageSaved(ctx, filterBy))
}

// ImageDeleted is the resolver for the imageDeleted field.
func (r *subscriptionResolver) ImageDeleted(ctx context.Context, filterBy *shared.ImageFilters) (<-chan *DeletedImage, error) {
	result := make(chan *DeletedImage)
	go func() {
		<-ctx.Done()
		close(result)
	}()
	return result, nil
}
