package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/application/image"
	"main/internal/domain/memo"
	"main/internal/shared"
	"path/filepath"
)

// URL is the resolver for the url field.
func (r *imageResolver) URL(ctx context.Context, obj *shared.ImageDTO, width *int, quality *int) (string, error) {
	var opts []image.SignOption
	if width != nil && *width < obj.Width {
		opts = append(opts, image.WithWidth(*width))
	}
	if quality != nil {
		opts = append(opts, image.WithQuality(*quality))
	}
	return r.signer.GenerateSignedURL(obj.AbsPath, opts...)
}

// Memo is the resolver for the memo field.
func (r *imageResolver) Memo(ctx context.Context, obj *shared.ImageDTO) (*shared.MemoDTO, error) {
	relPath, err := filepath.Rel(r.rootDir, obj.AbsPath)
	if err != nil {
		return nil, err
	}
	id := memo.EncodeID(relPath)
	return r.app.Memo(ctx, id)
}

// Image returns ImageResolver implementation.
func (r *Resolver) Image() ImageResolver { return &imageResolver{r} }

type imageResolver struct{ *Resolver }
