package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/application/image"
	"main/internal/shared"
)

// URL is the resolver for the url field.
func (r *imageResolver) URL(ctx context.Context, obj *shared.ImageDTO, width *int, quality *int) (string, error) {
	var opts []image.SignOption
	if width != nil && *width < obj.Width {
		opts = append(opts, image.WithWidth(*width))
	}
	if quality != nil {
		opts = append(opts, image.WithQuality(*quality))
	}
	return r.signer.GenerateSignedURL(obj.AbsPath, opts...)
}

// RawURL is the resolver for the rawURL field.
func (r *imageResolver) RawURL(ctx context.Context, obj *shared.ImageDTO) (string, error) {
	return r.signer.GenerateSignedURL(obj.AbsPath, image.WithRaw())
}

// Note is the resolver for the note field.
func (r *imageResolver) Note(ctx context.Context, obj *shared.ImageDTO) (*shared.NoteDTO, error) {
	// 配套文件：以图片文件名加上额外后缀的文件为配套文件
	noteRelPath := obj.RelPath + ".md"
	return r.app.NoteByRelPath(ctx, noteRelPath)
}

// Image returns ImageResolver implementation.
func (r *Resolver) Image() ImageResolver { return &imageResolver{r} }

type imageResolver struct{ *Resolver }
