package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/application/session"
)

// MarkImage is the resolver for the markImage field.
func (r *mutationResolver) MarkImage(ctx context.Context, input MarkImageInput) (*MarkImagePayload, error) {
	err := r.App.MarkImage(
		ctx,
		input.SessionID,
		input.ImageID,
		session.Action(input.Action),
	)
	if err != nil {
		return nil, err
	}

	sess, err := r.App.GetSession(ctx, input.SessionID)
	if err != nil {
		return nil, err
	}

	return &MarkImagePayload{
		Session:          sess,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
