package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
	"path"
	"strings"
)

// Title is the resolver for the title field.
func (r *memoResolver) Title(ctx context.Context, obj *shared.MemoDTO) (string, error) {
	return strings.TrimSuffix(path.Base(obj.RelPath), ".md"), nil
}

// Memo returns MemoResolver implementation.
func (r *Resolver) Memo() MemoResolver { return &memoResolver{r} }

type memoResolver struct{ *Resolver }
