package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
	"main/internal/shared"
)

// MemoUpdated is the resolver for the memoUpdated field.
func (r *subscriptionResolver) MemoUpdated(ctx context.Context, id scalar.ID) (<-chan *shared.MemoDTO, error) {
	return SubscriptionFromSeq(ctx, r.app.MemoUpdated(ctx, id))
}

// MemoSaved is the resolver for the memoSaved field.
func (r *subscriptionResolver) MemoSaved(ctx context.Context, filterBy *shared.MemoFilters) (<-chan *shared.MemoDTO, error) {
	return SubscriptionFromSeq(ctx, r.app.MemoSaved(ctx, filterBy))
}
