// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"main/internal/enum"
	"main/internal/scalar"
	"main/internal/shared"
)

type Node interface {
}

type CommitChangesInput struct {
	SessionID        scalar.ID            `json:"sessionId"`
	WriteActions     *shared.WriteActions `json:"writeActions"`
	ClientMutationID *string              `json:"clientMutationId,omitempty"`
}

type CommitChangesPayload struct {
	Written          int                `json:"written"`
	Session          *shared.SessionDTO `json:"session,omitempty"`
	ClientMutationID *string            `json:"clientMutationId,omitempty"`
}

type CreateSessionInput struct {
	Filter           *shared.ImageFilters `json:"filter"`
	TargetKeep       int                  `json:"targetKeep"`
	DirectoryID      scalar.ID            `json:"directoryId"`
	ClientMutationID *string              `json:"clientMutationId,omitempty"`
}

type CreateSessionPayload struct {
	Session          *shared.SessionDTO `json:"session"`
	ClientMutationID *string            `json:"clientMutationId,omitempty"`
}

// 删除事件载体，仅保留图片ID（原文件已不存在）
type DeletedImage struct {
	ID scalar.ID `json:"id"`
}

type MarkImageInput struct {
	SessionID        scalar.ID                         `json:"sessionId"`
	ImageID          scalar.ID                         `json:"imageId"`
	Action           enum.Enum[shared.ImageActionMeta] `json:"action"`
	Duration         *scalar.Duration                  `json:"duration,omitempty"`
	ClientMutationID *string                           `json:"clientMutationId,omitempty"`
}

type MarkImagePayload struct {
	Session          *shared.SessionDTO `json:"session"`
	ClientMutationID *string            `json:"clientMutationId,omitempty"`
}

type Meta struct {
	RootAbsPath string `json:"rootAbsPath"`
	RootPath    string `json:"rootPath"`
	Version     string `json:"version"`
}

type MoveImagesInput struct {
	// 当前所在的目录ID
	DirectoryID scalar.ID `json:"directoryId"`
	// 图片过滤条件
	FilterBy *shared.ImageFilters `json:"filterBy"`
	// 目标目录相对路径，相对于当前所在的目录（支持 ..）
	ToDirectoryRelPath string  `json:"toDirectoryRelPath"`
	ClientMutationID   *string `json:"clientMutationId,omitempty"`
}

type MoveImagesPayload struct {
	// 移动成功的图片数量
	MovedCount int `json:"movedCount"`
	// 移动的目标目录绝对物理路径，用于前端通过协议调起资源管理器并定位
	TargetAbsoluteDirectory string  `json:"targetAbsoluteDirectory"`
	ClientMutationID        *string `json:"clientMutationId,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type RatingCount struct {
	Rating int `json:"rating"`
	Count  int `json:"count"`
}

type Subscription struct {
}

type UndoInput struct {
	SessionID        scalar.ID `json:"sessionId"`
	ClientMutationID *string   `json:"clientMutationId,omitempty"`
}

type UndoPayload struct {
	Session          *shared.SessionDTO `json:"session,omitempty"`
	ClientMutationID *string            `json:"clientMutationId,omitempty"`
}

type UpdateImageMetadataInput struct {
	ID     scalar.ID `json:"id"`
	Rating *int      `json:"rating,omitempty"`
	Label  *string   `json:"label,omitempty"`
}

type UpdateSessionInput struct {
	SessionID        scalar.ID            `json:"sessionId"`
	TargetKeep       *int                 `json:"targetKeep,omitempty"`
	Filter           *shared.ImageFilters `json:"filter,omitempty"`
	ClientMutationID *string              `json:"clientMutationId,omitempty"`
}

type UpdateSessionPayload struct {
	Session          *shared.SessionDTO `json:"session"`
	ClientMutationID *string            `json:"clientMutationId,omitempty"`
}
