// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"main/internal/application/image"
	"main/internal/application/session"
	"main/internal/enum"
	"main/internal/scalar"
	"main/internal/shared"
)

type CommitChangesInput struct {
	SessionID        scalar.ID             `json:"sessionId"`
	WriteActions     *session.WriteActions `json:"writeActions"`
	ClientMutationID *string               `json:"clientMutationId,omitempty"`
}

type CommitChangesPayload struct {
	Success          bool                `json:"success"`
	Written          int                 `json:"written"`
	Failed           int                 `json:"failed"`
	Errors           []string            `json:"errors"`
	Session          *session.SessionDTO `json:"session,omitempty"`
	ClientMutationID *string             `json:"clientMutationId,omitempty"`
}

type CreateSessionInput struct {
	Filter           *image.ImageFilters `json:"filter"`
	TargetKeep       int                 `json:"targetKeep"`
	DirectoryID      scalar.ID           `json:"directoryId"`
	ClientMutationID *string             `json:"clientMutationId,omitempty"`
}

type CreateSessionPayload struct {
	Session          *session.SessionDTO `json:"session"`
	ClientMutationID *string             `json:"clientMutationId,omitempty"`
}

type MarkImageInput struct {
	SessionID        scalar.ID                         `json:"sessionId"`
	ImageID          scalar.ID                         `json:"imageId"`
	Action           enum.Enum[shared.ImageActionMeta] `json:"action"`
	ClientMutationID *string                           `json:"clientMutationId,omitempty"`
}

type MarkImagePayload struct {
	Session          *session.SessionDTO `json:"session"`
	ClientMutationID *string             `json:"clientMutationId,omitempty"`
}

type Meta struct {
	RootPath string `json:"rootPath"`
	Version  string `json:"version"`
}

type Mutation struct {
}

type Query struct {
}

type RatingCount struct {
	Rating int `json:"rating"`
	Count  int `json:"count"`
}

type Subscription struct {
}

type UndoInput struct {
	SessionID        scalar.ID `json:"sessionId"`
	ClientMutationID *string   `json:"clientMutationId,omitempty"`
}

type UndoPayload struct {
	Session          *session.SessionDTO `json:"session,omitempty"`
	ClientMutationID *string             `json:"clientMutationId,omitempty"`
}

type UpdateSessionInput struct {
	SessionID        scalar.ID           `json:"sessionId"`
	TargetKeep       *int                `json:"targetKeep,omitempty"`
	Filter           *image.ImageFilters `json:"filter,omitempty"`
	ClientMutationID *string             `json:"clientMutationId,omitempty"`
}

type UpdateSessionPayload struct {
	Session          *session.SessionDTO `json:"session"`
	ClientMutationID *string             `json:"clientMutationId,omitempty"`
}
