// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"main/internal/enum"
	"main/internal/scalar"
	"main/internal/shared"
	"time"
)

// 全局节点接口，所有实体类型统一实现此接口以支持 ID 解析。
type Node interface {
}

type ApprovePairingRequestInput struct {
	Code string `json:"code"`
}

// 将文件附加到系统剪贴板，使剪贴板内容可直接粘贴为文件
type AttachFileToClipboardInput struct {
	// 要附加到剪贴板的文件路径列表，可以是绝对路径或相对于根目录的路径
	Paths []string `json:"paths"`
	// 随机数，用于验证剪贴板数据来源。客户端需先在本地写入 meta[name="io.github.natescarlet.image-funnel.nonce"] 为此随机数的 HTML 格式剪贴板内容，服务端通过读取本地剪贴板以判断操作是否发自本机客户端。
	Nonce            string  `json:"nonce"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type AttachFileToClipboardPayload struct {
	// 剪贴板增强功能是否受支持
	Supported        bool    `json:"supported"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type AuthStatus struct {
	IsTrustedDevice bool `json:"isTrustedDevice"`
	IsTrustedIP     bool `json:"isTrustedIP"`
	CanAccess       bool `json:"canAccess"`
}

type BeginWebAuthnLoginInput struct {
	Dummy *bool `json:"dummy,omitempty"`
}

type BeginWebAuthnLoginPayload struct {
	Options    any    `json:"options"`
	SessionKey string `json:"sessionKey"`
}

type BeginWebAuthnRegistrationInput struct {
	SetupToken *string `json:"setupToken,omitempty"`
}

type BeginWebAuthnRegistrationPayload struct {
	Options    any    `json:"options"`
	SessionKey string `json:"sessionKey"`
}

// 提交当前筛选结果，将操作映射为 XMP 评分写入 sidecar 文件。
// 已提交过的图片在后续提交中会跳过（避免重复写入），但符合 filter 的图片会继续参与后续筛选。
type CommitChangesInput struct {
	// 会话ID
	SessionID scalar.ID `json:"sessionId"`
	// 各操作对应的评分写入配置
	WriteActions     *shared.WriteActions `json:"writeActions"`
	ClientMutationID *string              `json:"clientMutationId,omitempty"`
}

type CommitChangesPayload struct {
	// 实际写入磁盘的 XMP 文件数量（跳过已符合目标评分的图片）
	Written int `json:"written"`
	// 本次提交成功处理的图片总数（包括实际修改和匹配无需修改的图片）
	Matched int `json:"matched"`
	// 提交后的会话对象
	Session          *shared.SessionDTO `json:"session,omitempty"`
	ClientMutationID *string            `json:"clientMutationId,omitempty"`
}

type CreateNoteInput struct {
	// 所在目录的 ID
	DirectoryID scalar.ID `json:"directoryId"`
	// 笔记主文件名（例如 README，若包含 .md 会自动处理）
	Name string `json:"name"`
	// 笔记内容
	Content string `json:"content"`
}

// 创建新筛选会话
type CreateSessionInput struct {
	// 初始筛选条件，确定哪类图片进入筛选队列
	Filter *shared.ImageFilters `json:"filter"`
	// 目标保留图片数量
	TargetKeep int `json:"targetKeep"`
	// 要创建会话的目录ID
	DirectoryID      scalar.ID `json:"directoryId"`
	ClientMutationID *string   `json:"clientMutationId,omitempty"`
}

type CreateSessionPayload struct {
	// 创建的会话对象
	Session          *shared.SessionDTO `json:"session"`
	ClientMutationID *string            `json:"clientMutationId,omitempty"`
}

type DeleteDeviceInput struct {
	ID scalar.ID `json:"id"`
}

// 图片删除事件载体，仅保留图片ID
type DeletedImage struct {
	ID scalar.ID `json:"id"`
}

// 手动派发图片钩子的输入
type DispatchImageHookInput struct {
	// 图片筛选条件
	FilterBy *shared.ImageFilters `json:"filterBy"`
	// 要触发的钩子 ID
	HookID scalar.ID `json:"hookId"`
	// 客户端突变标识
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

// 手动派发图片钩子的返回数据
type DispatchImageHookPayload struct {
	// 客户端突变标识
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

// 手动派发笔记钩子的输入
type DispatchNoteHookInput struct {
	// 笔记 ID
	NoteID scalar.ID `json:"noteId"`
	// 要触发的钩子 ID
	HookID scalar.ID `json:"hookId"`
	// 客户端突变标识
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

// 手动派发笔记钩子的返回数据
type DispatchNoteHookPayload struct {
	// 客户端突变标识
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

// 手动清空回收站
type EmptyTrashPayload struct {
	// 此次被真正清理的历史数量
	ClearedCount     int     `json:"clearedCount"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type FinishWebAuthnLoginInput struct {
	SessionKey string `json:"sessionKey"`
	Response   string `json:"response"`
}

type FinishWebAuthnLoginPayload struct {
	// 访问令牌引用
	AccessToken string `json:"accessToken"`
	// 访问令牌的有效秒数（相对时间）
	AccessTokenExpiresIn int `json:"accessTokenExpiresIn"`
	// 刷新令牌引用
	RefreshToken string `json:"refreshToken"`
	// 刷新令牌的有效秒数（相对时间）
	RefreshTokenExpiresIn int `json:"refreshTokenExpiresIn"`
	// 登录成功后返回当前设备信息
	Device *shared.DeviceDTO `json:"device"`
}

type FinishWebAuthnRegistrationInput struct {
	SessionKey string  `json:"sessionKey"`
	Response   string  `json:"response"`
	SetupToken *string `json:"setupToken,omitempty"`
}

type FinishWebAuthnRegistrationPayload struct {
	// 访问令牌引用（注册成功后返回）
	AccessToken *string `json:"accessToken,omitempty"`
	// 访问令牌的有效秒数（相对时间）
	AccessTokenExpiresIn *int `json:"accessTokenExpiresIn,omitempty"`
	// 刷新令牌引用（注册成功后返回）
	RefreshToken *string `json:"refreshToken,omitempty"`
	// 刷新令牌的有效秒数（相对时间）
	RefreshTokenExpiresIn *int `json:"refreshTokenExpiresIn,omitempty"`
	// 注册成功时返回已创建的设备信息
	Device         *shared.DeviceDTO         `json:"device,omitempty"`
	PairingRequest *shared.PairingRequestDTO `json:"pairingRequest,omitempty"`
}

// 指令参数自动完成输入
type HookAutocompleteInput struct {
	// 钩子 ID
	HookID scalar.ID `json:"hookId"`
	// 笔记 ID
	NoteID *scalar.ID `json:"noteId,omitempty"`
	// 光标前的当前行完整文本
	LinePrefix string `json:"linePrefix"`
	// 当前正在输入的词
	Query string `json:"query"`
}

// 对当前图片执行分类操作（保留/搁置/排除）
type MarkImageInput struct {
	// 会话ID
	SessionID scalar.ID `json:"sessionId"`
	// 要标记的图片ID
	ImageID scalar.ID `json:"imageId"`
	// 标记动作
	Action enum.Enum[shared.ImageActionMeta] `json:"action"`
	// 用户操作耗时（毫秒），用于统计分析
	Duration         *scalar.Duration `json:"duration,omitempty"`
	ClientMutationID *string          `json:"clientMutationId,omitempty"`
}

type MarkImagePayload struct {
	// 操作后的会话对象
	Session          *shared.SessionDTO `json:"session"`
	ClientMutationID *string            `json:"clientMutationId,omitempty"`
}

// 应用元信息
type Meta struct {
	// 应用根目录的绝对路径
	RootAbsPath string `json:"rootAbsPath"`
	RootPath    string `json:"rootPath"`
	// 当前应用版本号
	Version string `json:"version"`
	// 配置的基础URL
	BaseURL string `json:"baseURL"`
	// 服务启动时间
	ServerStartTime time.Time `json:"serverStartTime"`
}

// 将符合条件的图片移动到指定子目录
type MoveImagesInput struct {
	// 当前所在的目录ID
	DirectoryID scalar.ID `json:"directoryId"`
	// 需要移动的图片筛选条件
	FilterBy *shared.ImageFilters `json:"filterBy"`
	// 目标目录
	ToDirectory      *shared.PathInput `json:"toDirectory"`
	ClientMutationID *string           `json:"clientMutationId,omitempty"`
}

type MoveImagesPayload struct {
	// 移动成功的图片数量
	MovedCount int `json:"movedCount"`
	// 目标目录的绝对物理路径，可用于前端调起系统资源管理器定位
	TargetAbsoluteDirectory string  `json:"targetAbsoluteDirectory"`
	ClientMutationID        *string `json:"clientMutationId,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

// 图片评分分布统计
type RatingCount struct {
	// XMP 评分值
	Rating int `json:"rating"`
	// 持有该评分的图片数量
	Count int `json:"count"`
}

// 刷新 Token 的输入参数
type RefreshTokenInput struct {
	// 刷新令牌引用
	RefreshToken string `json:"refreshToken"`
}

// 刷新 Token 的响应数据
type RefreshTokenPayload struct {
	// 新的访问令牌引用（如果是 Cookie 模式，则为引用字符串；如果是 Inline 模式，则为 JWT 字符串）
	AccessToken string `json:"accessToken"`
	// 访问令牌的有效秒数（相对时间）
	AccessTokenExpiresIn int `json:"accessTokenExpiresIn"`
	// 新的刷新令牌引用
	RefreshToken string `json:"refreshToken"`
	// 刷新令牌的有效秒数（相对时间）
	RefreshTokenExpiresIn int `json:"refreshTokenExpiresIn"`
}

type RejectPairingRequestInput struct {
	Code string `json:"code"`
}

type SetDirectoryStateInput struct {
	// 目录的ID
	ID scalar.ID `json:"id"`
	// 目录的新状态数据
	State *shared.DirectoryStateDTO `json:"state"`
}

type Subscription struct {
}

// 将符合条件的图片及其配套文件移到回收站
type TrashImagesInput struct {
	DirectoryID scalar.ID            `json:"directoryId"`
	FilterBy    *shared.ImageFilters `json:"filterBy"`
	// 删除时附带的额外说明消息，支持多行文本
	Message          *string `json:"message,omitempty"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type TrashImagesPayload struct {
	HistoryID        scalar.ID `json:"historyId"`
	MovedCount       int       `json:"movedCount"`
	ClientMutationID *string   `json:"clientMutationId,omitempty"`
}

// 撤销上一次标记操作，支持跨轮撤销
type UndoInput struct {
	// 会话ID
	SessionID        scalar.ID `json:"sessionId"`
	ClientMutationID *string   `json:"clientMutationId,omitempty"`
}

type UndoPayload struct {
	// 撤销后的会话对象，无操作可撤销时返回null
	Session          *shared.SessionDTO `json:"session,omitempty"`
	ClientMutationID *string            `json:"clientMutationId,omitempty"`
}

// 撤销回收站的删除操作，将文件移回原处
type UndoTrashInput struct {
	HistoryID        scalar.ID `json:"historyId"`
	ClientMutationID *string   `json:"clientMutationId,omitempty"`
}

type UpdateImageMetadataInput struct {
	// 图片ID
	ID scalar.ID `json:"id"`
	// 新的评分值（0-5），为null表示不修改
	Rating *int `json:"rating,omitempty"`
	// 新的颜色标签，为null表示不修改
	Label *string `json:"label,omitempty"`
}

// 批量更新符合条件的图片的元数据
type UpdateImagesMetadataInput struct {
	// 过滤条件
	FilterBy *shared.ImageFilters `json:"filterBy"`
	// 新的评分值（0-5），为null表示不修改
	Rating *int `json:"rating,omitempty"`
	// 新的颜色标签，为null表示不修改
	Label            *string `json:"label,omitempty"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

type UpdateImagesMetadataPayload struct {
	// 更新成功的图片数量
	UpdatedCount     int     `json:"updatedCount"`
	ClientMutationID *string `json:"clientMutationId,omitempty"`
}

// 更新会话配置（目标保留数量、筛选条件）
type UpdateSessionInput struct {
	// 会话ID
	SessionID scalar.ID `json:"sessionId"`
	// 新的目标保留数量，为null表示不修改
	TargetKeep *int `json:"targetKeep,omitempty"`
	// 新的筛选条件。
	Filter           *shared.ImageFilters `json:"filter,omitempty"`
	ClientMutationID *string              `json:"clientMutationId,omitempty"`
}

type UpdateSessionPayload struct {
	// 更新后的会话对象
	Session          *shared.SessionDTO `json:"session"`
	ClientMutationID *string            `json:"clientMutationId,omitempty"`
}
