package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"

	"github.com/99designs/gqlgen/graphql"
)

// MoveImages is the resolver for the moveImages field.
func (r *mutationResolver) MoveImages(ctx context.Context, input MoveImagesInput) (*MoveImagesPayload, error) {
	var filter shared.ImageFilters
	if input.FilterBy != nil {
		filter = *input.FilterBy
	}

	movedCount, targetAbsDir, err := r.app.MoveImages(ctx, input.DirectoryID, filter, input.ToDirectoryRelPath)
	if err != nil {
		graphql.AddError(ctx, err)
		return nil, err
	}

	return &MoveImagesPayload{
		MovedCount:              movedCount,
		TargetAbsoluteDirectory: targetAbsDir,
		ClientMutationID:        input.ClientMutationID,
	}, nil
}
