package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
	"strings"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id scalar.ID) (Node, error) {
	if strings.HasPrefix(id.String(), "dir:") {
		return r.app.Directory(ctx, id)
	}
	return nil, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
