package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
	"path"
	"strings"
)

// Title is the resolver for the title field.
func (r *noteResolver) Title(ctx context.Context, obj *shared.NoteDTO) (string, error) {
	return strings.TrimSuffix(path.Base(obj.RelPath), ".md"), nil
}

// Note returns NoteResolver implementation.
func (r *Resolver) Note() NoteResolver { return &noteResolver{r} }

type noteResolver struct{ *Resolver }
