package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
	"main/internal/shared"
)

// NoteUpdated is the resolver for the noteUpdated field.
func (r *subscriptionResolver) NoteUpdated(ctx context.Context, id scalar.ID) (<-chan *shared.NoteDTO, error) {
	return SubscriptionFromSeq(ctx, r.app.NoteUpdated(ctx, id))
}

// NoteSaved is the resolver for the noteSaved field.
func (r *subscriptionResolver) NoteSaved(ctx context.Context, filterBy *shared.NoteFilters) (<-chan *shared.NoteDTO, error) {
	return SubscriptionFromSeq(ctx, r.app.NoteSaved(ctx, filterBy))
}
