package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// NotificationChannels is the resolver for the notificationChannels field.
func (r *queryResolver) NotificationChannels(ctx context.Context, first *int, after *string) (*shared.NotificationChannelConnectionDTO, error) {
	return r.app.NotificationChannels(ctx, first, after)
}
