package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// LatestNotification is the resolver for the latestNotification field.
func (r *notificationChannelResolver) LatestNotification(ctx context.Context, obj *shared.NotificationChannelDTO) (*shared.NotificationDTO, error) {
	return r.app.Notification(ctx, obj.LatestNotificationID)
}

// NotificationChannel returns NotificationChannelResolver implementation.
func (r *Resolver) NotificationChannel() NotificationChannelResolver {
	return &notificationChannelResolver{r}
}

type notificationChannelResolver struct{ *Resolver }
