package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, channel string, filterBy *shared.NotificationFilters, first *int, after *string) (*shared.NotificationConnectionDTO, error) {
	var f shared.NotificationFilters
	if filterBy != nil {
		f = *filterBy
	}

	return r.app.Notifications(ctx, channel, f, first, after)
}
