package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// Notification is the resolver for the notification field.
func (r *notificationChangedEventResolver) Notification(ctx context.Context, obj *shared.NotificationChangedEventDTO) (*shared.NotificationDTO, error) {
	return r.app.Notification(ctx, obj.NotificationID)
}

// NotificationChangedEvent returns NotificationChangedEventResolver implementation.
func (r *Resolver) NotificationChangedEvent() NotificationChangedEventResolver {
	return &notificationChangedEventResolver{r}
}

type notificationChangedEventResolver struct{ *Resolver }
