package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// PairingRequestCreated is the resolver for the pairingRequestCreated field.
func (r *subscriptionResolver) PairingRequestCreated(ctx context.Context) (<-chan *shared.PairingRequestDTO, error) {
	return SubscriptionFromSeq(ctx, r.app.SubscribePairingRequestCreated(ctx))
}
