package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/apperror"
	"main/internal/application/device"
	"main/internal/shared"
)

// PairingRequests is the resolver for the pairingRequests field.
func (r *queryResolver) PairingRequests(ctx context.Context) ([]*shared.PairingRequestDTO, error) {
	// 校验当前设备是否受信任，或者来源 IP 是否受信任
	if !device.IsTrustedDevice(ctx) && !device.IsTrustedIP(ctx) {
		return nil, apperror.New("UNAUTHORIZED", "Unauthorized access", "未授权的访问请求")
	}

	return r.app.PairingRequests(ctx)
}
