package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// PairingRequestUpdated is the resolver for the pairingRequestUpdated field.
func (r *subscriptionResolver) PairingRequestUpdated(ctx context.Context, code string) (<-chan *shared.PairingRequestDTO, error) {
	seq := func(yield func(*shared.PairingRequestDTO, error) bool) {
		for dto, err := range r.app.SubscribeParingRequestUpdated(ctx) {
			if err != nil {
				if !yield(nil, err) {
					return
				}
				continue
			}
			if dto.Code == code {
				if !yield(dto, nil) {
					return
				}
			}
		}
	}
	return SubscriptionFromSeq(ctx, seq)
}
