package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"time"
)

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input RefreshTokenInput) (*RefreshTokenPayload, error) {
	accessTokenRef, refreshTokenRef, accessExpiresAt, refreshExpiresAt, err := r.app.RefreshToken(ctx, input.RefreshToken)
	if err != nil {
		return nil, err
	}
	return &RefreshTokenPayload{
		AccessToken:           accessTokenRef,
		AccessTokenExpiresIn:  int(time.Until(accessExpiresAt).Seconds()),
		RefreshToken:          refreshTokenRef,
		RefreshTokenExpiresIn: int(time.Until(refreshExpiresAt).Seconds()),
	}, nil
}
