package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// RejectPairingRequest is the resolver for the rejectPairingRequest field.
func (r *mutationResolver) RejectPairingRequest(ctx context.Context, input RejectPairingRequestInput) (bool, error) {
	err := r.app.RejectPairingRequest(ctx, input.Code)
	return err == nil, err
}
