package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// RenameDirectory is the resolver for the renameDirectory field.
func (r *mutationResolver) RenameDirectory(ctx context.Context, input RenameDirectoryInput) (*RenameDirectoryPayload, error) {
	newDirectoryID, err := r.app.Rename(ctx, input.DirectoryID, input.NewName)
	if err != nil {
		return nil, err
	}

	// 目录 ID 随重命名改变，按新 ID 查询重命名后的目录供前端跳转
	dir, err := r.app.Directory(ctx, newDirectoryID)
	if err != nil {
		return nil, err
	}

	return &RenameDirectoryPayload{
		Directory:        dir,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
