package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/domain/directory"
	"main/internal/shared"
)

// RootDirectory is the resolver for the rootDirectory field.
func (r *queryResolver) RootDirectory(ctx context.Context) (*shared.DirectoryDTO, error) {
	return r.app.Directory(ctx, directory.EncodeID("."))
}
