package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// SendNotification is the resolver for the sendNotification field.
func (r *mutationResolver) SendNotification(ctx context.Context, input SendNotificationInput) (*SendNotificationPayload, error) {
	var opts []shared.SendNotificationOption
	if input.NotAfter != nil {
		opts = append(opts, shared.WithNotAfter(*input.NotAfter))
	}
	if input.NotBefore != nil {
		opts = append(opts, shared.WithNotBefore(*input.NotBefore))
	}
	if input.DetailsURL != nil {
		opts = append(opts, shared.WithDetailsURL(*input.DetailsURL))
	}

	dto, didCreate, err := r.app.SendNotification(
		ctx,
		input.Tag,
		input.Channel,
		input.Title,
		input.Body,
		input.Priority,
		opts...,
	)
	if err != nil {
		return nil, err
	}

	return &SendNotificationPayload{
		Notification:     dto,
		DidCreate:        didCreate,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
