package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// SendNotification is the resolver for the sendNotification field.
func (r *mutationResolver) SendNotification(ctx context.Context, input SendNotificationInput) (*SendNotificationPayload, error) {
	dto, didCreate, err := r.app.SendNotification(
		ctx,
		input.Tag,
		input.Channel,
		input.Title,
		input.Body,
		input.Priority,
		input.NotAfter,
		input.NotBefore,
	)
	if err != nil {
		return nil, err
	}

	return &SendNotificationPayload{
		Notification:     dto,
		DidCreate:        didCreate,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
