package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/apperror"
	"main/internal/scalar"
	"main/internal/shared"
)

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, id scalar.ID) (*shared.SessionDTO, error) {
	return apperror.IgnoreNotFound(r.app.Session(ctx, id))
}

// Directory is the resolver for the directory field.
func (r *sessionResolver) Directory(ctx context.Context, obj *shared.SessionDTO) (*shared.DirectoryDTO, error) {
	return r.app.Directory(ctx, obj.DirectoryID)
}

// CreatedAt is the resolver for the createdAt field.
func (r *sessionResolver) CreatedAt(ctx context.Context, obj *shared.SessionDTO) (string, error) {
	return obj.CreatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *sessionResolver) UpdatedAt(ctx context.Context, obj *shared.SessionDTO) (string, error) {
	return obj.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"), nil
}

// NextImages is the resolver for the nextImages field.
func (r *sessionResolver) NextImages(ctx context.Context, obj *shared.SessionDTO, count *int) ([]*shared.ImageDTO, error) {
	if count == nil {
		count = new(int)
		*count = -1
	}
	return r.app.NextImages(ctx, obj.ID, *count)
}

// Session returns SessionResolver implementation.
func (r *Resolver) Session() SessionResolver { return &sessionResolver{r} }

type sessionResolver struct{ *Resolver }
