package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
	"main/internal/shared"
)

// SessionUpdated is the resolver for the sessionUpdated field.
func (r *subscriptionResolver) SessionUpdated(ctx context.Context, sessionID scalar.ID) (<-chan *shared.SessionDTO, error) {
	ch := make(chan *shared.SessionDTO, 10)

	go func() {
		defer close(ch)

		for dto, err := range r.app.SubscribeSession(ctx) {
			if err != nil {
				return
			}
			if dto.ID == sessionID {
				select {
				case ch <- dto:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return ch, nil
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
