package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
	"main/internal/shared"
)

// SessionUpdated is the resolver for the sessionUpdated field.
func (r *subscriptionResolver) SessionUpdated(ctx context.Context, id scalar.ID) (<-chan *shared.SessionDTO, error) {
	return SubscriptionFromSeq(ctx, func(yield func(*shared.SessionDTO, error) bool) {
		for dto, err := range r.app.SubscribeSession(ctx) {
			if err != nil {
				if !yield(nil, err) {
					return
				}
				continue
			}
			if dto.ID == id {
				if !yield(dto, nil) {
					return
				}
			}
		}
	})
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
