package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// SetDirectoryState is the resolver for the setDirectoryState field.
func (r *mutationResolver) SetDirectoryState(ctx context.Context, input SetDirectoryStateInput) (*SetDirectoryStatePayload, error) {
	dir, err := r.app.SetState(ctx, input.ID, input.State)
	if err != nil {
		return nil, err
	}
	return &SetDirectoryStatePayload{
		Directory:        dir,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
