package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
	"main/internal/shared"
)

// SuggestDirectories is the resolver for the suggestDirectories field.
func (r *queryResolver) SuggestDirectories(ctx context.Context, directoryID scalar.ID, input shared.PathInput) ([]*shared.DirectoryDTO, error) {
	return r.app.SuggestDirectories(ctx, directoryID, input)
}
