package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
	"main/internal/shared"
	"os"
	"path/filepath"
)

// CoverImage is the resolver for the coverImage field.
func (r *trashHistoryItemResolver) CoverImage(ctx context.Context, obj *shared.TrashHistoryItemDTO) (*shared.ImageDTO, error) {
	if obj.CoverImageAbsPath == "" {
		return nil, nil
	}
	info, err := os.Stat(obj.CoverImageAbsPath)
	if err != nil {
		return nil, nil
	}

	filename := filepath.Base(obj.CoverImageAbsPath)
	relPath, err := filepath.Rel(r.rootDir, obj.CoverImageAbsPath)
	if err != nil {
		relPath = ""
	}

	return &shared.ImageDTO{
		ID:       scalar.ToID("trash-cover:" + obj.ID.String()),
		Filename: filename,
		Size:     info.Size(),
		AbsPath:  obj.CoverImageAbsPath,
		RelPath:  filepath.ToSlash(relPath),
		ModTime:  info.ModTime(),
	}, nil
}

// TrashHistoryItem returns TrashHistoryItemResolver implementation.
func (r *Resolver) TrashHistoryItem() TrashHistoryItemResolver { return &trashHistoryItemResolver{r} }

type trashHistoryItemResolver struct{ *Resolver }
