package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/apperror"
	"main/internal/shared"
	"path/filepath"
)

// CoverImage is the resolver for the coverImage field.
func (r *trashHistoryItemResolver) CoverImage(ctx context.Context, obj *shared.TrashHistoryItemDTO) (*shared.ImageDTO, error) {
	if obj.CoverImageAbsPath == "" {
		return nil, nil
	}

	relPath, err := filepath.Rel(r.rootDir, obj.CoverImageAbsPath)
	if err != nil {
		return nil, err
	}

	img, err := r.app.ImageByRelPath(ctx, filepath.ToSlash(relPath))
	return apperror.IgnoreNotFound(img, err)
}

// TrashHistoryItem returns TrashHistoryItemResolver implementation.
func (r *Resolver) TrashHistoryItem() TrashHistoryItemResolver { return &trashHistoryItemResolver{r} }

type trashHistoryItemResolver struct{ *Resolver }
