package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
	"main/internal/shared"
)

// TrashImages is the resolver for the trashImages field.
func (r *mutationResolver) TrashImages(ctx context.Context, input TrashImagesInput) (*TrashImagesPayload, error) {
	var filter shared.ImageFilters
	if input.FilterBy != nil {
		filter = *input.FilterBy
	}

	var message string
	if input.Message != nil {
		message = *input.Message
	}

	historyId, movedCount, err := r.app.TrashImages(ctx, input.DirectoryID, filter, message)
	if err != nil {
		return nil, err
	}

	return &TrashImagesPayload{
		HistoryID:        scalar.ToID(historyId),
		MovedCount:       movedCount,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
