package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// TrashHistory is the resolver for the trashHistory field.
func (r *queryResolver) TrashHistory(ctx context.Context, first *int, after *string) (*shared.TrashHistoryConnectionDTO, error) {
	return r.app.TrashHistory(ctx, first, after)
}
