package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// UndoTrash is the resolver for the undoTrash field.
func (r *mutationResolver) UndoTrash(ctx context.Context, input UndoTrashInput) (*shared.UndoTrashResultDTO, error) {
	res, err := r.app.UndoTrash(ctx, input.HistoryID.String())
	if err != nil {
		return nil, err
	}
	res.ClientMutationID = input.ClientMutationID
	return res, nil
}
