package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// Undo is the resolver for the undo field.
func (r *mutationResolver) Undo(ctx context.Context, input UndoInput) (*UndoPayload, error) {
	err := r.App.Undo(ctx, input.SessionID)
	if err != nil {
		return nil, err
	}

	sess, err := r.App.GetSession(ctx, input.SessionID)
	if err != nil {
		return nil, err
	}

	return &UndoPayload{
		Session:          sess,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
