package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
)

// UnsendNotification is the resolver for the unsendNotification field.
func (r *mutationResolver) UnsendNotification(ctx context.Context, id scalar.ID) (*UnsendNotificationPayload, error) {
	deletedId, err := r.app.UnsendNotification(ctx, id)
	if err != nil {
		return nil, err
	}

	return &UnsendNotificationPayload{
		DeletedID: deletedId,
	}, nil
}
