package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/apperror"
)

// UnsendNotification is the resolver for the unsendNotification field.
func (r *mutationResolver) UnsendNotification(ctx context.Context, input UnsendNotificationInput) (*UnsendNotificationPayload, error) {
	id, err := r.app.UnsendNotification(ctx, input.Tag)
	if err != nil {
		return nil, err
	}

	notif, err := apperror.IgnoreNotFound(r.app.Notification(ctx, id))
	if err != nil {
		return nil, err
	}

	return &UnsendNotificationPayload{
		Notification:     notif,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
