package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
	"main/internal/shared"
)

// UpdateNote is the resolver for the updateNote field.
func (r *mutationResolver) UpdateNote(ctx context.Context, id scalar.ID, content string) (*shared.NoteDTO, error) {
	if err := r.app.UpdateNote(ctx, id, content); err != nil {
		return nil, err
	}
	return r.app.Note(ctx, id)
}
