package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
	"main/internal/shared"
)

// UpdateLabel is the resolver for the updateLabel field.
func (r *mutationResolver) UpdateLabel(ctx context.Context, sessionID scalar.ID, imageID scalar.ID, label string) (*shared.ImageDTO, error) {
	return r.app.UpdateLabel(ctx, sessionID, imageID, label)
}
