package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/scalar"
	"time"
)

// UpdateNotification is the resolver for the updateNotification field.
func (r *mutationResolver) UpdateNotification(ctx context.Context, id scalar.ID, input UpdateNotificationInput) (*UpdateNotificationPayload, error) {
	var readAt *time.Time
	if input.ReadAt.IsSet() {
		readAt = input.ReadAt.Value()
	}
	var dismissedAt *time.Time
	if input.DismissedAt.IsSet() {
		dismissedAt = input.DismissedAt.Value()
	}

	dto, err := r.app.Update(ctx, id, readAt, dismissedAt)
	if err != nil {
		return nil, err
	}

	return &UpdateNotificationPayload{
		Notification:     dto,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
