package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// UpdateSession is the resolver for the updateSession field.
func (r *mutationResolver) UpdateSession(ctx context.Context, input UpdateSessionInput) (*UpdateSessionPayload, error) {
	// Convert ImageFiltersInput to application layer ImageFilters
	var filter *shared.ImageFilters
	if input.Filter != nil {
		filter = &shared.ImageFilters{
			Rating: input.Filter.Rating,
		}
	}

	err := r.app.UpdateSession(
		ctx,
		input.SessionID,
		input.TargetKeep,
		filter,
	)
	if err != nil {
		return nil, err
	}

	sess, err := r.app.GetSession(ctx, input.SessionID)
	if err != nil {
		return nil, err
	}

	return &UpdateSessionPayload{
		Session:          sess,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
