package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"time"

	"main/internal/shared"
)

// UpdateNotification is the resolver for the updateNotification field.
func (r *mutationResolver) UpdateNotification(ctx context.Context, input UpdateNotificationInput) (*UpdateNotificationPayload, error) {
	var opts []shared.UpdateNotificationOption
	if input.ReadAt.IsSet() {
		t := input.ReadAt.Value()
		at := time.Time{}
		if t != nil {
			at = *t
		}
		opts = append(opts, shared.WithUpdateReadAt(at))
	}
	if input.DismissedAt.IsSet() {
		t := input.DismissedAt.Value()
		at := time.Time{}
		if t != nil {
			at = *t
		}
		opts = append(opts, shared.WithUpdateDismissedAt(at))
	}

	if err := r.app.UpdateNotification(ctx, input.ID, opts...); err != nil {
		return nil, err
	}

	notif, err := r.app.Notification(ctx, input.ID)
	if err != nil {
		return nil, err
	}

	return &UpdateNotificationPayload{
		Notification:     notif,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
