package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// UpdateSession is the resolver for the updateSession field.
func (r *mutationResolver) UpdateSession(ctx context.Context, input UpdateSessionInput) (*UpdateSessionPayload, error) {
	err := r.app.UpdateSession(
		ctx,
		input.SessionID,
		input.TargetKeep,
		input.Filter,
	)
	if err != nil {
		return nil, err
	}

	sess, err := r.app.Session(ctx, input.SessionID)
	if err != nil {
		return nil, err
	}

	return &UpdateSessionPayload{
		Session:          sess,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
