package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"main/internal/shared"
)

// UpdateImagesMetadata is the resolver for the updateImagesMetadata field.
func (r *mutationResolver) UpdateImagesMetadata(ctx context.Context, input UpdateImagesMetadataInput) (*UpdateImagesMetadataPayload, error) {
	filterBy := shared.ImageFilters{}
	if input.FilterBy != nil {
		filterBy = *input.FilterBy
	}

	count, err := r.app.UpdateImagesMetadata(ctx, filterBy, input.Rating, input.Label)
	if err != nil {
		return nil, err
	}

	return &UpdateImagesMetadataPayload{
		UpdatedCount:     count,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
