package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// UpdateNote is the resolver for the updateNote field.
func (r *mutationResolver) UpdateNote(ctx context.Context, input UpdateNoteInput) (*UpdateNotePayload, error) {
	if err := r.app.UpdateNote(ctx, input.ID, input.Content); err != nil {
		return nil, err
	}
	note, err := r.app.Note(ctx, input.ID)
	if err != nil {
		return nil, err
	}
	return &UpdateNotePayload{
		Note:             note,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
