package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
)

// UpdateImageMetadata is the resolver for the updateImageMetadata field.
func (r *mutationResolver) UpdateImageMetadata(ctx context.Context, input UpdateImageMetadataInput) (*UpdateImageMetadataPayload, error) {
	err := r.app.UpdateImageMetadata(ctx, input.ID, input.Rating, input.Label)
	if err != nil {
		return nil, err
	}
	image, err := r.app.Image(ctx, input.ID)
	if err != nil {
		return nil, err
	}
	return &UpdateImageMetadataPayload{
		Image:            image,
		ClientMutationID: input.ClientMutationID,
	}, nil
}
