query BrowseDirectories(
  $id: ID!
  $filterBy: DirectoryFilters
  $first: Int
  $after: String
) {
  node(id: $id) {
    id
    ... on Directory {
      parentId
      relPath
      root
      directoriesV2(filterBy: $filterBy, first: $first, after: $after) {
        edges {
          cursor
          node {
            ...Directory
          }
        }
        nodes {
          ...Directory
        }
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
      }
    }
  }
}
