query DirectoryState($id: ID!) {
  node(id: $id) {
    ... on Directory {
      id
      state {
        browse {
          filterBy {
            id
            rating
            label
            query
          }
          filterNoteBy {
            id
            hidden
          }
        }
        lastSession {
          id
          filter {
            id
            rating
            label
            query
          }
          targetKeep
          commitActions {
            keepRating
            shelveRating
            rejectRating
          }
          createActions {
            keepRating
            shelveRating
            rejectRating
          }
        }
        updatedAt
      }
    }
  }
}
