query GetDirectories($path: String!) {
  directories(path: $path) {
    id
    path
    imageCount
    subdirectoryCount
    latestImageModTime
    latestImagePath
    latestImageUrl
    ratingCounts {
      rating
      count
    }
  }
}
