query GetDirectories($id: ID) {
  directory(id: $id) {
    id
    path
    imageCount
    subdirectoryCount
    latestImageModTime
    latestImagePath
    latestImageUrl
    ratingCounts {
      rating
      count
    }
    directories {
      id
      path
      imageCount
      subdirectoryCount
      latestImageModTime
      latestImagePath
      latestImageUrl
      ratingCounts {
        rating
        count
      }
    }
  }
}
