# import ./fragments/ImageFragment.gql

query GetDirectories($id: ID) {
  directory(id: $id) {
    id
    parentId
    path
    root
    imageCount
    subdirectoryCount
    latestImage {
      ...ImageFragment
      currentRating
      xmpExists
    }
    ratingCounts {
      rating
      count
    }
    directories {
      id
      parentId
      path
      root
      imageCount
      subdirectoryCount
      latestImage {
        ...ImageFragment
        currentRating
        xmpExists
      }
      ratingCounts {
        rating
        count
      }
    }
  }
}
