query notifications($filterBy: NotificationFiltersInput, $first: Int, $after: String) {
  notifications(filterBy: $filterBy, first: $first, after: $after) {
    edges {
      node {
        ...Notification
      }
      cursor
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
