query TrashHistory($first: Int, $after: String) {
  trashHistory(first: $first, after: $after) {
    edges {
      node {
        id
        totalFileCount
        totalFileSize
        trashedAt
        imageCount
        associatedFileCount
        srcRelPath
        coverImage {
          id
          url(width: 256)
        }
      }
      cursor
    }
    nodes {
      id
      totalFileCount
      totalFileSize
      trashedAt
      imageCount
      associatedFileCount
      srcRelPath
      coverImage {
        id
        url(width: 256)
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
